require("core.plugin_config.lsp-config")
require("core.plugin_config.treesitter")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.illuminate")
require("core.plugin_config.gitsigns")
require("core.plugin_config.neodev")
require("core.plugin_config.virt-column")
require("core.plugin_config.alpha")

